Repository AscEmu/AscEmu, pull requests merged in 2021-06, with the labels that each got.

#883 [Build] fix FreeBSD build
  .gitignore
  CMakeLists.txt
  dep/g3dlite/FileSystem.cpp
  dep/g3dlite/include/G3D/System.h
  dep/g3dlite/include/G3D/platform.h
  src/logonserver/CMakeLists.txt
  src/logonserver/Realm/RealmManager.hpp
  src/shared/CMakeLists.txt
  src/shared/Common.Legacy.h
  src/shared/Log.cpp
  src/shared/Network/SocketDefines.h
  src/shared/Network/SocketMgrFreeBSD.cpp
  src/shared/Network/SocketMgrFreeBSD.h
  src/shared/Threading/Mutex.cpp
  src/tools/vmap_tools/vmap4_extractor/vmapexport.cpp
  src/world/CMakeLists.txt
  src/world/Map/MapScriptInterface.cpp
  src/world/Units/Creatures/Vehicle.cpp
Labels: Platform: FreeBSD

#888 Fix WoWError when trying to accept quest
  src/world/Management/QuestMgr.cpp
Labels: Category: Quests/Gossips

#890 Transport Updates, Icecrown Citadel Scripts
  src/scripts/InstanceScripts/Wotlk/Raid_IceCrownCitadel.cpp
  src/scripts/InstanceScripts/Wotlk/Raid_IceCrownCitadel.h
  src/world/Management/TransporterHandler.cpp
  src/world/Management/TransporterHandler.h
  src/world/Map/MapMgr.cpp
  src/world/Objects/Transporter.cpp
  src/world/Objects/Transporter.h
  src/world/Spell/SpellAuraEffects.cpp
  src/world/Spell/SpellAuras.cpp
  src/world/Units/ThreatHandler.cpp
Labels: Category: Dungeons/Raids, Category: Gameobjects

#894 correct binary names inside vmaps.sh script
  src/tools/vmap_tools/vmaps.sh
Labels: Core - Extractors

#893 Fix BUILD_TOOLS on Linux systems
  src/tools/map_extractor/System.cpp
Labels: Core - Extractors, Platform: Linux

#899 Fixed Cataclysm Skill Update Fields
  src/world/Data/WoWPlayer.hpp
  src/world/Units/Players/Player.Legacy.cpp
  src/world/Units/Players/Player.cpp
  src/world/Units/Players/Player.h
Labels: Core - Player interface issues, Patch 4.3.4 - Cataclysm

#901 Implement most of negative auras
  src/world/Spell/SpellInfo.cpp
Labels: Category: Spells
