Repository AscEmu/AscEmu, pull requests merged in 2021-09, with the labels that each got.

#913 Move hardcoded scripts to db
  sql/world/updates/20210825-01_hardcoded_ai_scripts.sql
  sql/world/updates/20210829-00_hardcoded_ai_scripts.sql
  src/scripts/InstanceScripts/Classic/Instance_BlackfathomDeeps.cpp
  src/scripts/InstanceScripts/Classic/Instance_BlackfathomDeeps.h
  src/scripts/InstanceScripts/Classic/Instance_BlackrockDepths.cpp
  src/scripts/InstanceScripts/Classic/Instance_BlackrockDepths.h
  src/scripts/InstanceScripts/Classic/Instance_BlackrockSpire.cpp
  src/scripts/InstanceScripts/Classic/Instance_BlackrockSpire.h
  src/scripts/InstanceScripts/Classic/Instance_Deadmines.cpp
  src/scripts/InstanceScripts/Classic/Instance_Deadmines.h
  src/scripts/InstanceScripts/Classic/Instance_DireMaul.cpp
  src/scripts/InstanceScripts/Classic/Instance_DireMaul.h
  src/scripts/InstanceScripts/Classic/Instance_Gnomeregan.cpp
  src/scripts/InstanceScripts/Classic/Instance_Gnomeregan.h
  src/scripts/InstanceScripts/Classic/Instance_Maraudon.cpp
  src/scripts/InstanceScripts/Classic/Instance_Maraudon.h
  src/scripts/InstanceScripts/Classic/Instance_RagefireChasm.cpp
  src/scripts/InstanceScripts/Classic/Instance_RagefireChasm.h
  src/scripts/InstanceScripts/Classic/Instance_RazorfenDowns.cpp
  src/scripts/InstanceScripts/Classic/Instance_RazorfenDowns.h
  src/scripts/InstanceScripts/Classic/Instance_RazorfenKraul.cpp
  src/scripts/InstanceScripts/Classic/Instance_ScarletMonastery.cpp
  src/scripts/InstanceScripts/Classic/Instance_ScarletMonastery.h
  src/scripts/InstanceScripts/Classic/Instance_Scholomance.cpp
  src/scripts/InstanceScripts/Classic/Instance_Scholomance.h
  src/scripts/InstanceScripts/Classic/Instance_ShadowfangKeep.cpp
  src/scripts/InstanceScripts/Classic/Instance_ShadowfangKeep.h
  src/scripts/InstanceScripts/Classic/Instance_Stratholme.cpp
  src/scripts/InstanceScripts/Classic/Instance_TheTempleOfAtalHakkar.cpp
  src/scripts/InstanceScripts/Classic/Instance_Uldaman.cpp
  src/scripts/InstanceScripts/Classic/Instance_Uldaman.h
  src/scripts/InstanceScripts/Classic/Instance_WailingCaverns.cpp
  src/scripts/InstanceScripts/Classic/Instance_WailingCaverns.h
  src/scripts/InstanceScripts/Classic/Instance_ZulFarrak.cpp
  src/scripts/InstanceScripts/Classic/Instance_ZulFarrak.h
  src/scripts/InstanceScripts/Classic/Raid_BlackwingLair.cpp
  src/scripts/InstanceScripts/Classic/Raid_BlackwingLair.h
  src/scripts/InstanceScripts/Classic/Raid_MoltenCore.cpp
  src/scripts/InstanceScripts/Classic/Raid_MoltenCore.h
  src/scripts/InstanceScripts/Classic/Raid_OnyxiasLair.cpp
  src/scripts/InstanceScripts/Classic/Raid_OnyxiasLair.h
  src/scripts/InstanceScripts/Classic/Raid_WorldBosses.h
  src/scripts/InstanceScripts/Classic/Raid_ZulGurub.cpp
  src/scripts/InstanceScripts/Classic/Raid_ZulGurub.h
  src/world/Chat/Commands/DebugCommands.cpp
  src/world/Server/Master.cpp
  src/world/Units/Creatures/AIInterface.cpp
Labels: Database - Work, Category: Creatures, develop

#911 Delete Legacy Aura Handlers
  src/world/Spell/SpellAuras.h
Labels: Category: Spells

#918 adding MOP information to PlayerSkills
  src/scripts/SpellHandlers/LegacyFiles/ItemSpells_1.cpp
  src/scripts/SpellHandlers/LegacyFiles/MiscSpells.cpp
  src/world/Management/CMakeLists.txt
  src/world/Management/Item.h
  src/world/Management/Skill.h
  src/world/Management/Skill.hpp
  src/world/Spell/SpellInfo.cpp
  src/world/Units/Creatures/Creature.cpp
Labels: Patch 5.4.8 - Mop, Category: Players

#919 inclusion of arenas with TBC
  src/world/Server/WorldSession.cpp
Labels: Patch 2.4.3 - TBC, Category: Arena/Battleground

#920 added updated script for working with map, vmap, mmap
  src/tools/CMakeLists.txt
  src/tools/ToolsCataMop/vmap_tools/CMakeLists.txt
  src/tools/ToolsCataMop/vmap_tools/vmaps.bat
  src/tools/ToolsCataMop/vmap_tools/vmaps.sh
  src/tools/ae_tools.bat
  src/tools/ae_tools.sh
  src/tools/vmap_tools/CMakeLists.txt
  src/tools/vmap_tools/vmaps.bat
  src/tools/vmap_tools/vmaps.sh
Labels: Core - Extractors, Patch - All
