Repository AscEmu/AscEmu, pull requests merged in 2021-10, with the labels that each got.

#942 Fix group dungeon finder
  src/world/Management/LFG/LFGMgr.cpp
Labels: Category: Dungeons/Raids, Core - Functions, Patch 3.3.5 - WoTLK, Patch 4.3.4 - Cataclysm, Patch 5.4.8 - Mop

#941 Fix non-PCH builds
  src/logonserver/Auth/AuthSocket.cpp
  src/logonserver/Auth/AuthStructs.h
  src/logonserver/LogonCommServer/LogonCommServer.h
  src/logonserver/Server/IpBanMgr.h
  src/scripts/InstanceScripts/Setup.h
  src/scripts/QuestScripts/Setup.h
  src/shared/RC4Engine.h
  src/world/Chat/Commands/DebugCommands.cpp
  src/world/Management/Charter.hpp
  src/world/Map/MapCell.cpp
  src/world/Map/MapMgr.cpp
  src/world/Movement/Spline/MovementPacketBuilder.cpp
  src/world/Movement/WaypointDefines.h
  src/world/Objects/GameObject.cpp
  src/world/Objects/Transporter.cpp
  src/world/Server/EventableObject.cpp
  src/world/Server/Packets/Handlers/AreaTriggerHandler.cpp
  src/world/Server/Packets/Handlers/ChatHandler.cpp
  src/world/Server/Packets/Handlers/LootHandler.cpp
  src/world/Server/Packets/Handlers/MiscHandler.cpp
  src/world/Server/WorldSession.h
  src/world/Spell/Spell.Legacy.cpp
  src/world/Spell/Spell.cpp
  src/world/Spell/SpellEffects.Legacy.cpp
  src/world/Units/Creatures/AIInterface.cpp
  src/world/Units/Creatures/Creature.cpp
  src/world/Units/Creatures/Pet.cpp
  src/world/Units/Players/Player.Legacy.cpp
  src/world/Units/Unit.Legacy.cpp
  src/world/Units/UnitDefines.hpp
Labels: Platform: Windows, Platform: Linux

#939 Fix Magtheridon Spawns, Fix Wrong Creature Assisting Behaviour
  sql/world/updates/20211025-00_magtheridon_spawns.sql
  src/scripts/InstanceScripts/Tbc/Instance_TheShatteredHalls.cpp
  src/scripts/InstanceScripts/Tbc/Instance_TheUnderbog.cpp
  src/scripts/InstanceScripts/Tbc/Raid_Magtheridons_Lair.cpp
  src/scripts/InstanceScripts/Tbc/Raid_Magtheridons_Lair.h
  src/scripts/InstanceScripts/Tbc/Raid_SerpentshrineCavern.cpp
  src/world/Map/MapCell.cpp
  src/world/Map/MapMgr.cpp
  src/world/Map/MapMgr.h
  src/world/Map/TerrainMgr.cpp
  src/world/Map/TerrainMgr.h
  src/world/Objects/Object.cpp
  src/world/Server/Master.cpp
  src/world/Server/Script/CreatureAIScript.cpp
  src/world/Server/Script/CreatureAIScript.h
  src/world/Server/Script/ScriptMgr.cpp
  src/world/Spell/Spell.cpp
  src/world/Units/Creatures/AIInterface.cpp
  src/world/Units/Creatures/AIInterface.h
  src/world/Units/Creatures/Creature.cpp
  src/world/Units/Creatures/Pet.cpp
  src/world/Units/Players/Player.Legacy.cpp
  src/world/Units/Unit.cpp
Labels: Core - Scripts, Core - Map/Area Management, Category: Creatures
