Repository AscEmu/AscEmu, pull requests merged in 2022-06, with the labels that each got.

#1029 Deathknight Quests
  sql/world/updates/20220524-00_creature_properties.sql
  src/scripts/QuestScripts/Quest_DeathKnight.cpp
  src/scripts/SpellHandlers/Scripts/Mage.cpp
  src/world/Chat/Commands/debugcmds.cpp
  src/world/GameCata/Storage/DBCStructures.h
  src/world/GameClassic/Storage/DBCStructures.h
  src/world/GameMop/Storage/DBCStructures.h
  src/world/GameTBC/Storage/DBCStructures.h
  src/world/GameWotLK/Storage/DBCStructures.h
  src/world/Map/Maps/MapScriptInterface.h
  src/world/Map/Maps/WorldMap.cpp
  src/world/Server/Master.cpp
  src/world/Server/Script/CreatureAIScript.cpp
  src/world/Server/Script/CreatureAIScript.h
  src/world/Spell/Spell.Legacy.cpp
  src/world/Spell/Spell.Legacy.h
  src/world/Spell/Spell.cpp
  src/world/Spell/SpellEffects.Legacy.cpp
Labels: Category: Quests/Gossips, Core - Scripts

#1033 Automatically create directories for tools
  src/collision/Maps/TileAssembler.cpp
  src/tools/ToolsCataMop/mmaps_generator/PathGenerator.cpp
  src/tools/ToolsCataMop/vmap_tools/vmap4_assembler/VMapAssembler.cpp
  src/tools/mmaps_generator/PathGenerator.cpp
  src/tools/vmap_tools/vmap4_assembler/VMapAssembler.cpp
Labels: Core - Extractors

#1034 fix style code and delete unnecessary files
  README.md
  dep/bzip2/bzip.css
  dep/bzip2/xmlproc.sh
  dep/libmpq/libmpq/Makefile.am
  src/logonserver/Server/AccountMgr.cpp
  src/scripts/MiscScripts/GameObjects.cpp
  src/scripts/QuestScripts/Quest_Hellfire_Peninsula.cpp
  src/scripts/QuestScripts/Quest_Isle_of_QuelDanas.cpp
  src/scripts/QuestScripts/Quest_Paladin.cpp
  src/scripts/QuestScripts/Quest_StranglethornVale.cpp
  src/scripts/SpellHandlers/LegacyFiles/ItemSpells_1.cpp
  src/scripts/SpellHandlers/LegacyFiles/QIspells.cpp
  src/world/Management/ObjectMgr.cpp
  src/world/Management/WordFilter.cpp
  src/world/Movement/WaypointManager.cpp
  src/world/Server/WorldSocket.cpp
Labels: Core - Codestyle/Refactoring

#1038 fix compiling vmaps cata
  src/tools/ToolsCataMop/vmap_tools/vmap4_extractor/vmapexport.cpp
Labels: Core - Extractors, Patch 4.3.4 - Cataclysm

#1032 Add define NOMINMAX for MSVC compiler
  cmake/Compilers/msvc.cmake
  src/shared/Common.Legacy.h
Labels: Platform: Windows, Core - Codestyle/Refactoring, CMake

#1036 Fix spawns in Death Knight starting place for cata and mop
  sql/world/updates/20220611-00_spawns.sql
  src/world/Server/Master.cpp
Labels: Database - Work, Patch 4.3.4 - Cataclysm, Patch 5.4.8 - Mop, Category: Gameobjects, Category: Creatures

#1043 Some auras should be stackable from multiple casters
  src/world/Objects/Units/Unit.cpp
  src/world/Spell/SpellDefines.hpp
  src/world/Spell/SpellInfo.cpp
  src/world/Spell/SpellInfo.hpp
Labels: Category: Spells/Skills
