Repository AscEmu/AscEmu, pull requests merged in 2022-04, with the labels that each got.

#1001 Some refactoring to item enchantments
  src/scripts/LuaEngine/ItemFunctions.h
  src/scripts/SpellHandlers/LegacyFiles/RogueSpells.cpp
  src/world/Macros/ItemMacros.hpp
  src/world/Management/ItemInterface.cpp
  src/world/Management/ItemInterface.h
  src/world/Objects/CMakeLists.txt
  src/world/Objects/Item.Legacy.cpp
  src/world/Objects/Item.cpp
  src/world/Objects/Item.h
  src/world/Objects/ItemDefines.hpp
  src/world/Objects/Units/Players/Player.Legacy.cpp
  src/world/Objects/Units/Players/Player.cpp
  src/world/Objects/Units/Players/Player.h
  src/world/Objects/Units/Players/PlayerDefines.hpp
  src/world/Server/EventMgr.h
  src/world/Server/Packets/Handlers/CharacterHandler.cpp
  src/world/Server/Packets/Handlers/ItemHandler.cpp
  src/world/Server/Packets/Handlers/TradeHandler.cpp
  src/world/Server/WorldSession.cpp
  src/world/Server/WorldSession.h
  src/world/Spell/Spell.cpp
  src/world/Spell/SpellEffects.Legacy.cpp
  src/world/Spell/SpellProc_ClassScripts.cpp
Labels: Category: Items, Patch - All

#1005 start of classic version support 🎉
  src/world/Chat/ChatHandler.hpp
  src/world/Chat/CommandTableStorage.cpp
  src/world/Chat/Commands/CharacterCommands.cpp
  src/world/Objects/Units/Players/Player.Legacy.cpp
  src/world/Objects/Units/Players/Player.h
  src/world/Objects/Units/Unit.Legacy.cpp
  src/world/Server/Packets/Handlers/MiscHandler.cpp
  src/world/Server/WorldSession.cpp
  src/world/Spell/SpellAuras.Legacy.cpp
  src/world/Spell/Spell_ClassScripts.cpp
Labels: Patch 1.12.1 - Classic

#1010 Crashfix
  src/world/Server/Packets/Handlers/GroupHandler.cpp
Labels: Category: Players
